[package]
name = "cchain"
version = "0.1.0"
edition = "2021"
description = "A command line chain execution tool"
authors =  ["Xinyu Bao <baoxinyuworks@163.com>"]
readme = "README.md"
repository = "https://github.com/aspadax/gitars"
license = "MIT"

[dependencies]
