# .github/workflows/release.yml

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Install system dependencies
        run: |
          sudo apt-get update
          # Essential build tools for all targets
          sudo apt-get install -y \
            perl \
            pkg-config \
            libssl-dev \
            nasm \
            make \
            automake \
            libtool \
            ${{ matrix.deps }}
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # General environment variables
          RUSTFLAGS: '-C target-feature=+crt-static'  # Force static linking where possible
          # OpenSSL configuration
          OPENSSL_NO_VENDOR: 0  # Force vendored OpenSSL
          OPENSSL_STATIC: 1     # Force static linking
          # Linux-specific
          PKG_CONFIG_ALL_STATIC: 1
          # macOS-specific
          OSXCROSS_NO_INCLUDE_PATH_WARNINGS: 1
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          MINIFY: true
          TOOLCHAIN_VERSION: stable
          STATIC_LINKING: true
